#!/bin/sh

# config
EXECUTABLE=/usr/local/bin/p44ayabd
AYABSERIALPORT=/dev/ttyACM0
JSONAPIPORT=9999
STATEDIR=/var/lib/p44ayabd
LOGLEVEL=5

# make the state dir
mkdir -p ${STATEDIR}
chmod 777 ${STATEDIR}

# run the daemon
exec ${EXECUTABLE} \
  --ayabconnection ${AYABSERIALPORT} \
  --jsonapiport ${JSONAPIPORT} \
  --statedir ${STATEDIR} \
  -l ${LOGLEVEL} \
  2>&1 </dev/null
